routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Site\HomeController@index')->name('home');

Auth::routes();

Route::prefix('painel')->group(function(){
    Route::get('/', 'Admin\HomeController@index')->name('admin');

    /* Login Routing */
    Route::get('/login', 'Admin\Auth\LoginController@index')->name('login'); 
    Route::post('/login', 'Admin\Auth\LoginController@authenticate');
    
    /* Logout Route */
    Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');
    Route::get('/logout', 'Admin\Auth\LoginController@logout')->name('logout-get');

    /* Register Routing */
    Route::get('/register', 'Admin\Auth\RegisterController@index')->name('register'); 
    Route::post('/register', 'Admin\Auth\RegisterController@register');

    /* Users Routing */
    Route::resource('/users', 'Admin\UserController');

    /* Profile Routing */
    Route::get('/profile', 'Admin\ProfileController@index')->name('profile');
    Route::put('/profilesave', 'Admin\ProfileController@save')->name('profile.save');

    /* Lyrics Routing */
    Route::resource('/lyrics', 'Admin\LyricController');

    /* Lyrics Routing for Auth'd User */
    Route::resource('/authlyrics', 'Admin\LyricIdController');
});

app/Lyric.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cohensive\Embed\Facades\Embed;

class Lyric extends Model
{
    protected $guarded = ['id', 'created_at', 'updated_at'];
    protected $fillable = ['user_id', 'singer_id','title', 'info', 'video_url', 'lyric'];

    public function singer()
    {
        return $this->belongsTo(Singer::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // public function getVideoHtmlAttribute()
    // {
    //     $embed = Embed::make($this->video_url)->parseUrl();
        
    //     return $embed->getHtml();
    // }
}

app/Http/Controllers/Admin/LyricController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\Singer;
use App\Lyric;
use Illuminate\Http\Request;

class LyricController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
        $this->middleware('can:admin-content');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lyrics = Lyric::orderBy('lyric', 'ASC')->paginate('10');

        return view('admin.lyrics.index', [
            'lyrics' => $lyrics,
        ]);
    }

    /**
     * Show the form for creating a new resource
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // load the create form (app/views/lyrics/create.blade.php)
        return view('admin.lyrics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only([
            'title',
            // 'artist',
            'info',
            'video_url',
            'lyric'
        ]);

        $data['slug'] = Str::slug($data['title'], '-');

        $validator = Validator::make($data, [
            'title' => ['required', 'string', 'max:100'],
            'slug' => ['required', 'string', 'max:100', 'unique:lyrics'],
            // 'artist' => ['required', 'string', 'max:200'],
            'info' => ['string', 'max:100'],
            'video_url' => ['required', 'string', 'max:100', 'unique:lyrics'],
            'lyric' => ['required', 'string'],
        ]);

        if ($validator->fails()) {
            return redirect()->route('lyrics.create')
                ->withErrors($validator)
                ->withInput();
        }

        // if(strlen($data['video_url']) > 11)
        // {
        //     if (preg_match('%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i', $data['video_url'], $match))
        //     {
        //         return $match[1];
        //     }
        //     else
        //         return false;
        // }

        // return $data['video_url'];

        $lyric = new Lyric;
        $lyric->title = trim($data['title']);
        $lyric->slug = $data['slug'];
        $lyric->info = $data['info'];
        $lyric->video_url = substr($data['video_url'], -11);
        $lyric->lyric = $data['lyric'];
        $lyric->save();

        Session::flash('message', 'Música adicionada com sucesso!');
        return redirect()->route('lyrics.index');
    }

    /**
     * Display the specified resource
     *
     *
     .
     *
     * @param  \App\Lyric  $lyric
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $lyric = Lyric::find($id);

        return view('admin.lyrics.show', [
            'lyric' => $lyric
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lyric  $lyric
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lyric = Lyric::find($id);

        if ($lyric) {
            return view('admin.lyrics.edit', [
                'lyric' => $lyric
            ]);
        }

        return redirect()->route('lyrics.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lyric  $lyric
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $lyric = Lyric::find($id);

        if ($lyric) {
            $data = $request->only([
                'title',
                // 'artist',
                'info',
                'video_url',
                'lyric'
            ]);

            if ($lyric['title'] !== $data['title']) {
                $data['slug'] = Str::slug($data['title'], '-');

                $validator = Validator::make($data, [
                    'title' => ['required', 'string', 'max:100'],
                    'info' => ['string', 'max:100'],
                    'video_url' => ['required', 'string', 'max:100', 'url'],
                    'slug' => ['required', 'string', 'max:100', 'unique:lyrics'],
                    'lyric' => ['string'],
                ]);
            } else {
                $validator = Validator::make($data, [
                    'title' => ['required', 'string', 'max:100'],
                    'info' => ['string', 'max:100'],
                    'video_url' => ['required', 'string', 'max:100', 'url'],
                    'lyric' => ['string'],
                ]);
            }

            if ($validator->fails()) {
                return redirect()->route('lyrics.edit', [
                    'lyric' => $id
                ])
                    ->withErrors($validator)
                    ->withInput();
            }

            $lyric->title = trim($data['title']);
            $lyric->info = $data['info'];
            $lyric->video_url = $data['video_url'];
            $lyric->lyric = $data['lyric'];

            if (!empty($data['slug'])) {
                $lyric->slug = $data['slug'];
            }

            $lyric->save();
        }

        Session::flash('message', 'Música alterada com sucesso!');
        return redirect()->route('lyrics.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lyric  $lyric
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lyric = Lyric::find($id);
        $lyric->delete();

        Session::flash('message', 'Música excluída com sucesso!');
        return redirect()->route('lyrics.index');
    }
}

resources/views/admin/lyrics/create.blade.php
@extends('adminlte::page')

@section('title', 'Cadastrar Música')

@section('content_header')
<h1>Nova Música</h1>
@endsection

@section('content')

@if($errors->any())
<div class="alert alert-danger">
    <h5> <i class="icon fa s fa-ban"></i> Alerta! </h5>
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="card">
    <div class="card-body">
        <form class="form-horizontal" action="{{ route('lyrics.store') }}" method="POST">
            @csrf
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Título</label>
                <div class="col-sm-10">
                    <input type="text" name="title" value="{{old('title')}}"
                        class="form-control @error('title') is-invalid @enderror" />
                </div>
            </div>

            {{-- <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Artist</label>
                        <div class="col-sm-10">
                            <input type="text" name="artist" value="{{old('artist')}}" class="form-control
            @error('artist') is-invalid @enderror" />
    </div>
</div> --}}

<div class="form-group row">
    <label class="col-sm-2 col-form-label">Extra Info</label>
    <div class="col-sm-10">
        <input type="text" name="info" value="{{old('info')}}"
            class="form-control @error('info') is-invalid @enderror" />
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label">URL da Música</label>
    <div class="col-sm-10">
        <input type="url" name="video_url" value="{{old('video_url')}}"
            class="form-control @error('video_url') is-invalid @enderror" />
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label">Letra da Música</label>
    <div class="col-sm-10">
        <textarea name="lyric" id="lyric" cols="30" rows="10" class="form-control bodyfield2"></textarea>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
        <input type="submit" value="Salvar" class="btn btn-info" />
    </div>
</div>
</form>
</div>
</div>

{{-- <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

<script>
    tinymce.init({
        selector:'textarea.bodyfield',
        height:300,
        menubar:false,
    plugins:['link', 'table', 'image', 'autoresize', 'lists'],
    toolbar:'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | table | link image | bullist numlist',
    content_css:[
    '{{asset('css/tinymce.css')}}'
],
images_upload_url:'{{route('imageupload')}}', // criar a rota em api.php
image_upload_credentials:true,
convert_urls:false,
});
</script> --}}
@endsection

@section('css')
<link rel="stylesheet" href="/css/admin-styles.css">
@endsection

resources/views/admin/lyrics/edit.blade.php
@extends('adminlte::page')

@section('title', 'Cadastrar Música')

@section('content_header')
<h1>Nova Música</h1>
@endsection

@section('content')

@if($errors->any())
<div class="alert alert-danger">
    <h5> <i class="icon fa s fa-ban"></i> Alerta! </h5>
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="card">
    <div class="card-body">
        <form class="form-horizontal" action="{{ route('lyrics.update', ['lyric'=>$lyric->id]) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Título</label>
                <div class="col-sm-10">
                    <input type="text" name="title" value="{{$lyric->title}}"
                        class="form-control @error('title') is-invalid @enderror" />
                </div>
            </div>

            {{-- <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Artist</label>
                        <div class="col-sm-10">
                            <input type="text" name="artist" value="{{$lyric->artist}}" class="form-control
            @error('artist') is-invalid @enderror" />
    </div>
</div> --}}

<div class="form-group row">
    <label class="col-sm-2 col-form-label">Extra Info</label>
    <div class="col-sm-10">
        <input type="text" name="info" value="{{$lyric->info}}" class="form-control" />
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label">URL da Música</label>
    <div class="col-sm-10">
        <input type="url" name="video_url" value="{{$lyric->video_url}}"
            class="form-control @error('video_url') is-invalid @enderror" />
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label">Letra da Música</label>
    <div class="col-sm-10">
        <textarea name="lyric" id="lyric" row="15"
            class="form-control bodyfield @error('lyric') is-invalid @enderror">{{$lyric->lyric}}</textarea>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
        <input type="submit" value="Salvar" class="btn btn-info" />
    </div>
</div>
</form>
</div>
</div>

{{-- <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

<script>
    tinymce.init({
        selector:'textarea.bodyfield',
        height:300,
        menubar:false,
    plugins:['link', 'table', 'image', 'autoresize', 'lists'],
    toolbar:'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | table | link image | bullist numlist',
    // content_css:[
    // '{{asset('css/styles.css')}}'
// ]
images_upload_url:'{{route('imageupload')}}', // criar a rota em api.php
image_upload_credentials:true,
convert_urls:false,
});
</script> --}}
@endsection

@section('css')
<link rel="stylesheet" href="/css/admin-styles.css">
@endsection

resources/views/admin/lyrics/index.blade.php
@extends('adminlte::page')

@section('title', 'Lista de Músicas')

@section('content_header')
<h1>Listagem de Músicas
    <a href="{{ route('lyrics.create') }}" class="btn btn-sm btn-success ml-3 text-uppercase">Adicionar nova música</a>
</h1>
@endsection

@section('content')

<div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th width="50">ID</th>
                    <th>Artista</th>
                    <th>Título</th>
                    <th>Extra Info</th>
                    <th>URL da Música</th>
                    <th width="200">Ações</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($lyrics as $lyric)
                <tr>
                    <td>{{ $lyric->id }}</td>
                    <td>Nome do Artista</td>
                    <td>{{ $lyric->title }}</td>
                    <td>{{ $lyric->info }}</td>
                    <td>{{ $lyric->video_url }}</td>
                    <td>
                        <a href="{{ route('lyrics.show', ['lyric' => $lyric->id]) }}" target="_blank"
                            class="btn btn-sm btn-success">Ver</a>

                        <a href="{{ route('lyrics.edit', ['lyric' => $lyric->id]) }}"
                            class="btn btn-sm btn-info">Editar</a>

                        <form action="{{ route('lyrics.destroy', ['lyric' => $lyric->id]) }}" method="POST"
                            class="d-inline" onsubmit="return confirm('Tem certeza que deseja excluir este usuário?')">
                            @method('DELETE')
                            @csrf
                            <input type="submit" value="Excluir" class="btn btn-sm btn-danger">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
{{ $lyrics->links() }}
@endsection

resources/views/admin/lyrics/show.blade.php
@extends('adminlte::page')

@section('title', 'Músicas')

@section('content_header')
<h1>
    <a href="{{ route('lyrics.index') }}" class="btn btn-sm btn-info">Voltar à lista</a>
</h1>
@endsection

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card">
                    <div class="card-header">
                        <h3>
                            {{$lyric->title}}
                        </h3>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">Nome do cantor(a)/banda</h4><br><br>
                        <h6 class="card-subtitle text-muted">{{ $lyric->info }}</h6>
                    </div>
                    <img src="holder.js/100x180/" alt="">
                    <div class="card-body">
                        <div class="embeddedVideo">
                            <iframe src="https://www.youtube.com/embed/{{$lyric->video_url}}" frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                        </div><br><br>
                        <p class="lyrics-text" style="white-space: pre-line;">
                            {!!$lyric->lyric!!}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('css')
<link rel="stylesheet" href="/css/admin-styles.css">
@endsection